### ISSUE TITLE
Installation failing with Path argument error

### ISSUE THREAD

**Issue by steveculshaw** [aMediocreDad/stonetop#2]
I've tried to install the module, but I'm getting an error ... 
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined `

Installed:
Foundry VTT: 
Powered by the Apocalypse: 0.9.7

But tried it again and install worked !

**Comment by aMediocreDad** [comment]
Thanks for the heads up. This is a white space that snuck in somewhere when pasting:)
